### ISSUE TITLE
Test case for #1

### ISSUE THREAD

**Issue by knehez** [knehez/beton-teka#3]
Write a test case for #1

**Comment by aron123** [comment]
Angular unit testing tutorial:

https://logrocket.com/blog/angular-unit-testing/

**Comment by aron123** [comment]
Unit tests are added for the Login button: 6bca46fabc63d692d277723ac4906accd891b584

**Comment by Balx0** [comment]
test titles in login page: 0da881a145f2a968f81705845af7f3075eb4b814
