### ISSUE TITLE
https://www.npmjs.com/package/ngx-tree-dnd integráció

### ISSUE THREAD

**Issue by knehez** [knehez/beton-teka#4]
Építsük bele a kategória fa szerkesztéséhez.

**Comment by aron123** [comment]
A tree view megjelenítése össze lett kötve a backenddel. Az alábbi, dinamikus viselkedéseket kell még megvalósítani:

Funkciók kategória csomópont esetén:
- [ ] alkategória hozzáadása
- [ ] beton hozzáadása
- [ ] kategória törlése
- [ ] kategória nevének módosítása
- [ ] kategória drag engedélyezése/tiltása
- [ ] kategória drop engedélyezése/tiltása
- [ ] drag 'n' drop (új állapot mentése az adatbázisba)

Funkciók beton csomópont esetén:
- [ ] adatlap megnyitása
- [ ] beton adatainak módosítása 
- [ ] beton törlése
- [ ] drag 'n' drop (új állapot mentése az adatbázisba)

Fával kapcsolatos elvárások:
- [ ] a gyökér kategória ne legyen törölhető
- [ ] műveletek után growl notification jelezze a sikert/hibát
