### ISSUE TITLE
MySQL JSON column értelmezése

### ISSUE THREAD

**Issue by knehez** [knehez/beton-teka#5]
A dokumentáció alapján értelmezni kell:
https://www.npmjs.com/package/ngx-tree-dnd
https://scotch.io/tutorials/working-with-json-in-mysql

Hogyan lehetne a TypeORM-el összehozni ezt?

**Comment by aron123** [comment]
A következőképpen tárolhatóak el JS objektumok:

```ts
@Entity()
export class Concrete {
    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    name: string;

    @Column('json')
    properties: object;
}
```

**Comment by knehez** [comment]
Le kell tesztelni, hogy a fenti esetben hogyan lehet részlegesen keresni egy ilyen táblában?
Pl van egy ilyen táblánk amiben 3 sor van. Minden sor különböző számú és értékű név-érték párt tartalmaz. pl. az alábbi 2db-ot. (A mintát kézzel is érdemes létrehozni.)
```
{
  [
   name: "név1",
   value: "érték1"
  ],
  [
   name: "név2",
   value: "érték2"
  ],

}
```
Természetesen minden sorban a táblában a JSON mezőben különböző értékek vannak. Tehát hogyan lehetne keresni olyan rekordokat amelyek tartalmazzák a pl. a {név5: "value5"} értékeket? Fontos, hogy ne a teljes mezőtartalmat adjuk meg, hanem csak egy részét. Gyakorlatban ez azért kell, hogy le tudjuk kérdezni azokat a betonokat, amelyek szakítószilárdsága mondjuk 100, de más jellemzőjét nem tudjuk.

**Comment by aron123** [comment]
Kifejezetten JSON adatokban való keresésre a TypeORM nem biztosít függvényeket, de a .where() metóduson keresztül használható a [MySQL által biztosított szintaktika](https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html).

Van például egy tábla különböző adatokkal: https://i.imgur.com/uuDRj61.jpg
Erre készíthető olyan controller, ami visszaadja a keresett feltételeknek megfelelő rekordokat: https://i.imgur.com/KrXuIqM.jpg

Ez kb. így néz ki:

```ts
search = async (req, res) => {
    // TODO: check if req.body is an object
    // TODO: error handling
    
    const query = await this.model
                        .createQueryBuilder('concrete')
                        .select();

    const searchKeys = Object.keys(req.body);

    let idx = 0;
    for (const key of searchKeys) {
        const keyParamName = 'key' + idx;
        const valueParamName = 'value' + idx;

        query.andWhere(`properties -> :${keyParamName} = :${valueParamName}`, {
            [keyParamName]: `$.${key}`,
            [valueParamName]: req.body[key]
        });

        idx++;
    }

    const data = await query.getMany();
    res.json({
        success: true,
        data
    });
}
```
